### ISSUE TITLE
Can we have colours like the medals plugin?

### ISSUE THREAD

**Issue by Creatortag21** [Banalian/ExtraLeaderboardPositions#1]
Hey 
idk where to ask this so i opened an issue, it's not.

Can you add colours like the medal plugin does it? Have a red colour for a position above and blue for a position below. 

thank you,

love your plugin :)

**Comment by Creatortag21** [comment]
Hello,

https://i.imgur.com/unMsIfQ.png

there's an example. To enable this in ultimate medals you have to go to Additional Info and then check "Show Pesonal best delta time " and the negative time. 

thank you man appreciate it :D

**Comment by Banalian** [comment]
@Creatortag21 could you please check the PR? Is this what you had in mind ?
