### ISSUE TITLE
Watch a list of names

### ISSUE THREAD

**Issue by qwitwa** [Banalian/ExtraLeaderboardPositions#11]
I want to be able to see my friends' best times change when we play together

**Comment by Banalian** [comment]
That could be done, but it would require a club subscription, since this is a gold feature.

I'm gonna be working on a full cleaner backend API for this plugin, this is definitively a feature i'll look into :D !

**Comment by qwitwa** [comment]
I'm not sure I follow, but I don't think I was clear. I didn't mean best times, I meant filtering the current leaderboard of the server I'm in to show any friends on there and showing their current leaderboard time

**Comment by qwitwa** [comment]
Ah, I think I've misunderstood the purpose of this plugin. The data source you're pulling in is totally separate to the per server leaderboard, right? Whoops

**Comment by Banalian** [comment]
oh, you meant in a server !

Yeah sorry, this plugin allows you to check global leaderboard for maps (not a round/server local/current leaderboard :p)

you feature is still an interesting one for the global leaderboard imo, so i'll see if I can implement it when I make this kind of V2
