### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by Dennisvw99** [Banalian/ExtraLeaderboardPositions#14]
Missing an option to scale the textbox, I would like to be able to increase its size.

**Comment by Banalian** [comment]
Do you mean using something else beside the Openplanet Scaling option ? I'll have to look into it !

**Comment by Banalian** [comment]
I'm gonna close this issue, as after talking about it with someone from OP, they confirmed to me that the OP scaling button is the one you're supposed to use for this reason :p

Have a nice day, and feel free to reopen this or create another issue if anything else happens !
