### ISSUE TITLE
Suggestion GitHub Labels

### ISSUE THREAD

**Issue by MystWraith** [Banalian/ExtraLeaderboardPositions#20]
Just what it sounds like, that way it could separate suggestions from bugs/issues in GitHub to make it more clear.

**Comment by Banalian** [comment]
Hi ! There already are default labels, Do you mean a way for others to chose one when opening an issue ?

**Comment by MystWraith** [comment]
That is exactly what I mean, yes! That way I don't feel guilty about butting a suggestion in a general pile with issues that are a ton more pressing!

**Comment by Banalian** [comment]
Should be done thanks to the commit c1bb8d3 ! Thanks for the suggestion !
