### ISSUE TITLE
Medal color same as ultimate medals instead of rank

### ISSUE THREAD

**Issue by salem83** [Banalian/ExtraLeaderboardPositions#22]
Could it possible to assign the icon color to the medals instead of the rank (e.g. 10 = gold)?

- Champion: Reddish
- AT: Green
- Gold
- Silver
- Bronze
- PB: Cyan or custom

Thanks

**Comment by Banalian** [comment]
This is actually a planned feature ( see #19 )! I still need to take time to work on it, since it's a bit harder than planned, but this is definitively a mode I had in mind ! Thanks for the suggestion !
