### ISSUE TITLE
Leaderboard positions over 10,000 stopped working

### ISSUE THREAD

**Issue by roncli** [Banalian/ExtraLeaderboardPositions#24]
**Describe the bug**
When external API is on, any positions you have above 10,000 are listed as place 10,000 with the 10,000th place time.
When external API is off, any positions you have above 10,000 are listed as the position you entered, but still with the 10,000th place time.

This does not affect medals - you can still see the correct position and time of the medal.

**To Reproduce**
Add positions greater than 10,000. ie: 20,000, 30,000, 40,000.

**Expected behavior**
You get the times for those positions

**Screenshots**
With external API:
![image](https://github.com/Banalian/ExtraLeaderboardPositions/assets/498929/05997a7d-ee10-4807-8ddb-1f3773359988)

Without external API:
![image](https://github.com/Banalian/ExtraLeaderboardPositions/assets/498929/85aba87d-3842-42f2-bde4-58b37bbbd503)

**Additional context**
Having positions over 10,000 available in the API was a recent change... I wonder if that was a bug on Nadeo's part and they fixed it recently?  It's been this way for a couple weeks now.

**Comment by Banalian** [comment]
mmh, interesting, i'll take a look at it tomorrow, thanks for the report !

About the recent API change, according to Nadeo themselves it's not a bug and it will stay this way, so that's pretty cool !

**Comment by Banalian** [comment]
quick update, i'll look into it this weekend instead :p

**Comment by Banalian** [comment]
After searching on my end and asking questions, it appears that the change was only supposed to work on one endpoint (the one used to get the pb when using the external leaderboard), and wasn't supposed to work on the leaderboard endpoint (used to get all the positions). That sadly means that i'll need to revert these changes :/

Thanks again for the report !
