### ISSUE TITLE
API error:  response from ExtraLeaderboardAPI is null or empty

### ISSUE THREAD

**Issue by Agustin-Q** [Banalian/ExtraLeaderboardPositions#28]
**Describe the bug**
Having enabled external API, show player count and show percentage. The player count and the percentage are not shown.

**To Reproduce**
Enable from settings external API, show player count and show percentage, and enter a map.

**Expected behavior**
Player count and percentage should be shown.

**Screenshots**
![image](https://github.com/Banalian/ExtraLeaderboardPositions/assets/25281659/50c22eeb-ff30-44e4-b6c3-7704323f5086)

**Additional context**
Last week it was working ok on the winter season, when i started playing the spring season i did not work. Ive check a map of the winter season now and is not working there either

Logs:
```
[   ScriptRuntime] [17:16:41] [ExtraLeaderboardPositions]  Update(): new PB: 26021 [0:26.021]
[   ScriptRuntime] [17:16:41] [ExtraLeaderboardPositions]  Update(): new map uid: JtxsQPcGS9fs7lrl0xVPaMwVN97
[   ScriptRuntime] [17:16:43] [ExtraLeaderboardPositions]  RefreshLeaderboard(): updating leaderboard PB time from -1 to 26021 [0:26.021]
[   ScriptRuntime] [17:16:43] [ExtraLeaderboardPositions]  RefreshLeaderboard(): PB API attempt 1 at 0ms: sleeping 100ms to give API time to update
[   ScriptRuntime] [17:16:44] [ExtraLeaderboardPositions]  RefreshLeaderboard(): received valid API PB time 26021 [0:26.021], position 200000
[   ScriptRuntime] [17:16:44] [ExtraLeaderboardPositions]  RefreshLeaderboard(): getting all positions from API
[   ScriptRuntime] [17:16:45] [ExtraLeaderboardPositions]  Error calling API at url ' http://ec2-3-99-156-231.ca-central-1.compute.amazonaws.com:8080/ELP/api/leaderboard/map/JtxsQPcGS9fs7lrl0xVPaMwVN97/records?getplayercount=true&position=1,10,100,1000,10000&medal=1,2,3,4&' : 500 - 
[   ScriptRuntime] [17:16:45] [ExtraLeaderboardPositions]  response from ExtraLeaderboardAPI is null or empty
```

Thanks for the grate plugin!

**Comment by Banalian** [comment]
woops, should be fixed now, thanks a lot for the report!

**Comment by Agustin-Q** [comment]
Thanks!
