### ISSUE TITLE
Allow disabling the column with time % placement and the refresh button

### ISSUE THREAD

**Issue by XenoJiiva0053** [Banalian/ExtraLeaderboardPositions#39]
Allow disabling the column with time % placement and the refresh button

**Comment by Banalian** [comment]
Note: Refresh button can already get hidden with this
![image](https://github.com/user-attachments/assets/a13c77e3-4f10-4738-8f1c-822510b6e642)

**Comment by Banalian** [comment]
Woops, seems like the commit doesn't get linked, this was done with [8b149e7](https://github.com/Banalian/ExtraLeaderboardPositions/commit/8b149e7fd5c7c3590a9d6d82315c975cfad49a42), it'll be present with the next update :D
