### ISSUE TITLE
Add more invalid gamemodes

### ISSUE THREAD

**Issue by Fort-TM** [Banalian/ExtraLeaderboardPositions#43]
## Issue
The plugin tries to load the leaderboard for gamemodes without one, so it leads to incorrect or broken values.

## Suggestion
I think the best solution would be to add the gamemodes to invalidGamemodes

https://github.com/Banalian/ExtraLeaderboardPositions/blob/8b149e7fd5c7c3590a9d6d82315c975cfad49a42/Model/Data.as#L3-L7

The gamemodes that I found that cause issues are:
* TM_Platform_Local
* TM_Platform_Online*
* TM_RoyalTimeAttack_Local

Another solution would be to check the map type with app.Challenge.MapInfo.MapType instead, avoiding having to check for local and online variants, but would require some code restructure.

\*  Couldn't check nod explorer ingame since it's an online room, but got it from trackmania.io. Recommend double checking in case CurGameModeStr uses a different value

## Additional context
How it currently looks for platform (AT is not loaded, most likely because Platform stores 0 respawns as 0:00.000):
![image](https://github.com/user-attachments/assets/368e088b-0f40-4ae7-ade2-e4924c03431b)

and for local royal:
![image](https://github.com/user-attachments/assets/27df06d4-c6d0-403b-9ad8-e1e36be24eb0)

**Comment by Banalian** [comment]
woopsie x)

I'm already checking the maptype (using rootmap), but yeah, I mainly need to extend the supported gamemodes, thanks!

Just to be safe, "local" means just playing via the game as usual, or is it in a local "server" or something?

**Comment by Banalian** [comment]
Should be partially fixed by a599b2e0b1ceb3c903ad9437cac7b86366a909aa btw (not sure i'm catching the online mods, idk if app.RootMap.MapInfo.MapType contains the base mode or if I need to check individual submodes like _online and all

**Comment by Fort-TM** [comment]
Local loads the maps in solo, so if you go to local -> play map -> any royal map, it will load a map with the "TM_Royal" mapType in the "TM_RoyalTimeAttack_Local" game mode

>  idk if app.RootMap.MapInfo.MapType contains the base mode or if I need to check individual submodes like _online and all

Since you check the mapType, you don't need to worry about submodes, since mapType will still be "TM_Platform", "TM_Stunt", etc.

Thanks for the fix btw! Only thing remaining is local royal I believe

**Comment by Banalian** [comment]
I added the local mode in 11434cf6356a56558647ff3de2fc11407772aa45, forgot to update haha

I'll probably do an update with all that soon, just want to check one or two things before, in any case, thanks a lot for the report!
