### ISSUE TITLE
New Season, Plugin no longer works - Permissions

### ISSUE THREAD

**Issue by Jacobithekid** [Banalian/ExtraLeaderboardPositions#44]
**Describe the bug**
The plugin no longer works, whenever I view the logs it says:

"You currently don't have permission to view this plugin, you need the gold edition"

**To Reproduce**
Every time I enter any track

**Expected behavior**
I expect to see the leaderboard. I still have full club access, but the plugin or open planet isn't recognizing it 

**Screenshots**
Thanks for any help you can provide!

![image](https://github.com/user-attachments/assets/6b288cdd-3467-4f14-b21a-c3af3d15a55b)

**Comment by Jacobithekid** [comment]
I've tried refreshing open planet, trackmania, and uninstalling and reinstalling the plugin

**Comment by Banalian** [comment]
Interesting, may I get more info on your current sub? Do you have the OG gold, or do you have the recent one (bought after they removed the intermediate tier?)

In any case, even if the message talks about gold, in reality I check your individual permission, and this means that you don't have the permission to view map records 🤔

**Comment by Jacobithekid** [comment]
I feel so silly! My subscription ended right after season started but I still had this seasons tracks so didn't notice. I resubscribed and it works now, sorry to have bothered you and thanks for a great plug in!
