### ISSUE TITLE
Warrior/Champion medals use same position as PB

### ISSUE THREAD

**Issue by Fort-TM** [Banalian/ExtraLeaderboardPositions#45]
### **Describe the bug**
Both champion and warrior medals seem to use the same position as your PB if your time is faster than them

### **To Reproduce**
Get a warrior/champion medal (easiest one should be warrior on 01 this season)

### **Expected behavior**
Use the correct position

### **Screenshots**
First seen on Discord:
![image](https://github.com/user-attachments/assets/505534ed-ba02-4cfa-a800-b93ca1f60688)

### **Additional context**
The position will be wrong only for the medal slower than you. For example, here the champion medal is fine:

![image](https://github.com/user-attachments/assets/c9146f6b-1455-4e46-99a1-a999b14e1fab)

**Comment by Banalian** [comment]
Found the issue, thanks for reporting!


In case that's important for you, you don't get this issue when using the external API
![image](https://github.com/user-attachments/assets/6f62899c-b1c8-46b9-9ef8-bf3432b4ce1a)

**Comment by Fort-TM** [comment]
Thanks for the quick fix!
