### ISSUE TITLE
Author time position

### ISSUE THREAD

**Issue by Jenzu** [Banalian/ExtraLeaderboardPositions#5]
Hello!
I've been hunting author medals on old TOTD tracks and I was wondering if it's possible to add author time as an extra position?

**Comment by Banalian** [comment]
Hi !
After more investingation, the results aren't super precise using the API (the position i get seems to be offset, and the time is just the one i asked for, not the position's time) so i'm not really sure that i'll implement it yet (i think i'll do some base work to work with it, but i'm not sure i'll be able to make it a working feature in the neat future)

Thanks still for the input ! As said on discord, i'd really like this feature too, so maybe it'll come later !

I'll close this for now, but it'll stay in the back of my head, and feel free to reopen it if you want !

**Comment by Banalian** [comment]
Well..... I lied lmao, i worked on it tonight and ended up with something

![image](https://user-images.githubusercontent.com/64379456/163692666-2903eb98-1cb3-45f1-a5f1-b29e4fd14d57.png)

This is the kind of stuff I get (for information). the time is the medal time, and the position is the position needed to have that medal 🤔 

What do you think of it ?
